services:
    hgabka_payu.payment_factory:
        class: Hgabka\PayUBundle\Factory\PaymentFactory
        arguments: ["@doctrine", "@router", "@event_dispatcher", '']

    Hgabka\PayUBundle\Factory\PaymentFactory: "@hgabka_payu.payment_factory"